apiVersion: v1
kind: Service
metadata:
  name: hello-kyma-svc
spec:
  selector:
    app: "hello-kyma" # must match the pod's label
  ports:
    - protocol: "TCP"
      port: 80 # service port
      targetPort: 8080 # pod port
