apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: hello-kyma
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: hello-kyma
  rules:
    - accessStrategies:
        - handler: allow
      methods:
        - GET
      path: /.*
  service:
    name: hello-kyma-svc
    port: 80
