apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubernetes.io/change-cause: Upgrade to new release v1.0.1
  creationTimestamp: "2023-10-18T20:34:15Z"
  generation: 2
  labels:
    app.kubernetes.io/name: hello-kyma
  name: hello-kyma
  namespace: default
  resourceVersion: "158986"
  uid: 441bfc22-cce9-4f8a-904c-c7bbb75b81aa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-kyma
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-kyma
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: ghcr.io/sap-samples/kyma-runtime-learning-journey/hello-kyma:1.0.1
        imagePullPolicy: IfNotPresent
        name: hello-kyma
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-18T20:34:19Z"
    lastUpdateTime: "2023-10-18T20:34:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-18T20:34:15Z"
    lastUpdateTime: "2023-10-18T20:36:42Z"
    message: ReplicaSet "hello-kyma-54c4bfdf49" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
